apiVersion: clusterissuers.cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fibonacci-development-house-tls
spec:
  secretName: fibonacci-development-house
  dnsNames:
  - fibonacci.development.house
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - fibonacci.development.house
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibonacci.development.house
  keySize: 4096